### ISSUE TITLE
希望增加Space（间距）组件

### ISSUE THREAD

**Issue by 716774** [Ningstyle/mzl-ui#12]
类似于Antd的Space组件 太实用啦

[https://ant-design.gitee.io/components/space-cn/](https://ant-design.gitee.io/components/space-cn/)

```jsx
<Space>
·
·
·
</Space>
```

```jsx
<Space direction="vertical">
·
·
·
</Space>
```

**Comment by Ningstyle** [comment]
已增加，具体请查看：https://mzlui.codeym.com/#/mzlui/Space
