### ISSUE TITLE
官网是用什么写的？

### ISSUE THREAD

**Issue by Tyh2001** [Ningstyle/mzl-ui#13]
由仓库地址吗？

**Comment by 716774** [comment]
还不是vue写的，你就不会看作者主页吗。[https://github.com/Ningstyle/mzlui-doc/](https://github.com/Ningstyle/mzlui-doc/)

**Comment by Ningstyle** [comment]
是markdown加vue写得，markdown文件转vue组件的插件：vite-plugin-markdown，配合highlight.js，具体使用可以看：[](https://github.com/Ningstyle/mzlui-doc)

**Comment by Tyh2001** [comment]
@Ningstyle 加个微信吗兄弟？看你的组件库写的还不错，我也在写[组件库](https://github.com/Tyh2001/tyh-ui)，也许我们可以一起合作

wx：VirgoTyh
