### ISSUE TITLE
打包网页后 代码不能显示

### ISSUE THREAD

**Issue by YangQiao01** [Ningstyle/mzl-ui#37]
[plugin:rollup-plugin-dynamic-import-variables] invalid import "import(
        /* @vite-ignore */ `/packages/${props.compName}/doc/${props.demoName}.vue?raw`
      )". Variable absolute imports are not supported, imports must start with ./ in the static part of the import. For example: import(`./foo/${bar}.js`).    

```
if (isDev) {
    sourceCode.value = (
      await import(
        /* @vite-ignore */ `/packages/${props.compName}/doc/${props.demoName}.vue?raw`
      )
    ).default;
  } else {
    sourceCode.value = await fetch(
      `/packages/${props.compName}/doc/${props.demoName}.vue`
    ).then((res) => res.text());
  }
```
 打包网页应该进入到  else 里呀

**Comment by spark154204** [comment]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/48675578/182006529-aca963bc-b44b-4fc9-a6d8-f41f632c4ee7.png">
我这边打包可以使用

**Comment by Ningstyle** [comment]
打包组件后，用不到md文件，若打包网页，请将packages文件复制到dist下index.html同级，建议大家尊重版权，请勿私自部署其他服务器，这里只限学习交流
