### ISSUE TITLE
请问下全局引入样式为啥要这样

### ISSUE THREAD

**Issue by liaobiaowei** [Ningstyle/mzl-ui#40]

**Comment by liaobiaowei** [comment]
为啥要相对路径，为啥不能mzl-ui/dist/style.css

**Comment by Ningstyle** [comment]
这个您在vite或者webpack配置下就行哦

**Comment by liaobiaowei** [comment]
你是指样式那个位置，可以修改的？




-》-----------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ningstyle/mzl-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月23日(星期天) 凌晨0:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ningstyle/mzl-ui] 请问下全局引入样式为啥要这样 (Issue #40)





 
Closed #40 as completed.
